GET http://localhost:3001/todos HTTP/1.1

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
	"text": "Pick up Mumu"
}

###

DELETE http://localhost:3001/todo/delete/64330d782379e92241d17e1d


###

GET http://localhost:3001/todo/complete/

###

PUT http://localhost:3001/todo/update/60e585d86177f95ff0574323
Content-Type: application/json

{
	"text": "Go Shopping for Cloath"
}